install: 
    - "cp src/main/resources/configuration.properties.sample src/main/resources/configuration.properties"

language: java

script: "mvn clean package -B -e -Dsurefire.useFile=false -Djasper.threads=1"

jdk:
    - oraclejdk7

